# Generated by Django 3.2.9 on 2022-10-27 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degerlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degerlendirme', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=50)),
                ('faaliyet_alani', models.CharField(max_length=50)),
                ('il', models.CharField(max_length=50)),
                ('ilçe', models.CharField(max_length=50)),
                ('posta_kodu', models.IntegerField(blank=True, null=True)),
                ('telefon', models.IntegerField(blank=True, null=True)),
                ('eposta', models.EmailField(max_length=254)),
                ('unvan', models.CharField(max_length=50)),
                ('devlet_katkisi', models.BooleanField(default=False)),
                ('yetkil_ad', models.CharField(max_length=50)),
                ('yetkili_soyad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OgrenciBilgi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrenci_no', models.IntegerField(blank=True, null=True)),
                ('ogrenci_ad', models.CharField(max_length=50)),
                ('ogrenci_soyad', models.CharField(max_length=50)),
                ('ogrenci_eposta', models.EmailField(max_length=254)),
                ('ogrenci_telefon', models.IntegerField(blank=True, null=True)),
                ('ogrenci_fakülte', models.CharField(max_length=50)),
                ('ogrenci_bölüm', models.CharField(max_length=50)),
                ('ogrenci_sinif', models.IntegerField(blank=True, null=True)),
                ('ogrenci_dönem', models.IntegerField(blank=True, null=True)),
                ('ogrenci_adres', models.CharField(max_length=200)),
                ('ogrenci_dogum_tarihi', models.DateField()),
                ('ogrenci_dogum_yeri', models.CharField(max_length=50)),
                ('ogrenci_kayıt_tarihi', models.DateField()),
                ('ogrenci_tcno', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ogretmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sicil_no', models.IntegerField(blank=True, null=True)),
                ('ogretmen_ad', models.CharField(max_length=50)),
                ('ogretmen_soyad', models.CharField(max_length=50)),
                ('ogretmen_bolum', models.CharField(max_length=50)),
                ('ogretmen_fakulte', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OgrenciBasvuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigorta', models.IntegerField(blank=True, null=True)),
                ('uyruk', models.CharField(max_length=50)),
                ('prim', models.IntegerField(blank=True, null=True)),
                ('staj_sorumlusu', models.CharField(max_length=50)),
                ('tarih', models.DateField()),
                ('staj_tür', models.CharField(max_length=50)),
                ('baslama_tarih', models.DateField()),
                ('bitis_tarih', models.DateField()),
                ('is_günü', models.IntegerField(blank=True, null=True)),
                ('ogrenciB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koustaj.ogrencibilgi')),
            ],
        ),
        migrations.CreateModel(
            name='Komisyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogretmenk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koustaj.ogretmen')),
            ],
        ),
    ]
