# Generated by Django 3.2.9 on 2022-10-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koustaj', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degerlendirme',
            options={'verbose_name': 'Değerlendirme', 'verbose_name_plural': 'Değerlendirmeler'},
        ),
        migrations.AlterModelOptions(
            name='firma',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firmalar'},
        ),
        migrations.AlterModelOptions(
            name='komisyon',
            options={'verbose_name': 'Komisyon', 'verbose_name_plural': 'Komisyon'},
        ),
        migrations.AlterModelOptions(
            name='ogrencibasvuru',
            options={'verbose_name': 'Öğrenci Başvuru', 'verbose_name_plural': 'Öğrenci Başvuruları'},
        ),
        migrations.AlterModelOptions(
            name='ogrencibilgi',
            options={'verbose_name': 'Öğrenci Bilgi', 'verbose_name_plural': 'Öğrenci Bilgileri'},
        ),
        migrations.AlterModelOptions(
            name='ogretmen',
            options={'verbose_name': 'Öğretmen', 'verbose_name_plural': 'Öğretmenler'},
        ),
        migrations.AddField(
            model_name='firma',
            name='fax',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='degerlendirme',
            name='degerlendirme',
            field=models.BooleanField(default=False, verbose_name='Değerlendirme'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='devlet_katkisi',
            field=models.BooleanField(default=False, verbose_name='Devlet Katkısı'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='faaliyet_alani',
            field=models.CharField(max_length=50, verbose_name='Faaliyet Alanı'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='firma_adi',
            field=models.CharField(max_length=200, verbose_name='Firma Adı'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='il',
            field=models.CharField(max_length=50, verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='ilçe',
            field=models.CharField(max_length=50, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='posta_kodu',
            field=models.IntegerField(blank=True, null=True, verbose_name='Posta Kodu'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='telefon',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='unvan',
            field=models.CharField(max_length=50, verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='yetkil_ad',
            field=models.CharField(max_length=50, verbose_name='Yetkili Ad'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='yetkili_soyad',
            field=models.CharField(max_length=50, verbose_name='Yetkili Soyad'),
        ),
        migrations.AlterField(
            model_name='ogrencibasvuru',
            name='baslama_tarih',
            field=models.DateField(verbose_name='Başlama Tarihi'),
        ),
        migrations.AlterField(
            model_name='ogrencibasvuru',
            name='bitis_tarih',
            field=models.DateField(verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='ogrencibasvuru',
            name='is_günü',
            field=models.IntegerField(blank=True, null=True, verbose_name='İş Günü'),
        ),
        migrations.AlterField(
            model_name='ogrencibasvuru',
            name='prim',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prim'),
        ),
        migrations.AlterField(
            model_name='ogrencibasvuru',
            name='sigorta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sigorta'),
        ),
        migrations.AlterField(
            model_name='ogrencibasvuru',
            name='staj_sorumlusu',
            field=models.CharField(max_length=50, verbose_name='Staj Sorumlusu'),
        ),
        migrations.AlterField(
            model_name='ogrencibasvuru',
            name='staj_tür',
            field=models.CharField(max_length=50, verbose_name='Staj Tür'),
        ),
        migrations.AlterField(
            model_name='ogrencibasvuru',
            name='tarih',
            field=models.DateField(verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='ogrencibasvuru',
            name='uyruk',
            field=models.CharField(max_length=50, verbose_name='Uyruk'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_ad',
            field=models.CharField(max_length=50, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_adres',
            field=models.CharField(max_length=200, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_bölüm',
            field=models.CharField(max_length=50, verbose_name='Bölüm'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_dogum_tarihi',
            field=models.DateField(verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_dogum_yeri',
            field=models.CharField(max_length=50, verbose_name='Doğum Yeri'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_dönem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dönem'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_eposta',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_fakülte',
            field=models.CharField(max_length=50, verbose_name='Fakülte'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_kayıt_tarihi',
            field=models.DateField(verbose_name='Öğren Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Öğrenci No'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_sinif',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sınıf'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_soyad',
            field=models.CharField(max_length=50, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_tcno',
            field=models.IntegerField(blank=True, null=True, verbose_name='TC'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_telefon',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='ogretmen',
            name='ogretmen_ad',
            field=models.CharField(max_length=50, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='ogretmen',
            name='ogretmen_bolum',
            field=models.CharField(max_length=50, verbose_name='Bölüm'),
        ),
        migrations.AlterField(
            model_name='ogretmen',
            name='ogretmen_fakulte',
            field=models.CharField(max_length=50, verbose_name='Fakülte'),
        ),
        migrations.AlterField(
            model_name='ogretmen',
            name='ogretmen_soyad',
            field=models.CharField(max_length=50, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='ogretmen',
            name='sicil_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sicil No'),
        ),
    ]
