# Generated by Django 3.2.9 on 2022-10-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koustaj', '0002_auto_20221028_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='degerlendirme',
            name='staj_basvuru',
            field=models.BooleanField(default=False, verbose_name='Staj Başvuru Formu'),
        ),
        migrations.AddField(
            model_name='degerlendirme',
            name='staj_degerlendirme',
            field=models.BooleanField(default=False, verbose_name='Staj Değerlendirme Formu'),
        ),
        migrations.AddField(
            model_name='degerlendirme',
            name='staj_rapor',
            field=models.BooleanField(default=False, verbose_name='Staj Raporu'),
        ),
    ]
