# Generated by Django 3.2.9 on 2022-10-28 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koustaj', '0003_auto_20221028_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='adres',
            field=models.CharField(max_length=250, null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='firma',
            name='oBasvuru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koustaj.ogrencibasvuru'),
        ),
    ]
