# Generated by Django 3.2.9 on 2022-10-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koustaj', '0004_auto_20221028_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ogrencibasvuru',
            old_name='is_günü',
            new_name='is_gunu',
        ),
        migrations.RenameField(
            model_name='ogrencibasvuru',
            old_name='staj_tür',
            new_name='staj_tur',
        ),
        migrations.RenameField(
            model_name='ogrencibilgi',
            old_name='ogrenci_bölüm',
            new_name='ogrenci_bolum',
        ),
        migrations.RenameField(
            model_name='ogrencibilgi',
            old_name='ogrenci_dönem',
            new_name='ogrenci_donem',
        ),
        migrations.RenameField(
            model_name='ogrencibilgi',
            old_name='ogrenci_fakülte',
            new_name='ogrenci_fakulte',
        ),
        migrations.AddField(
            model_name='firma',
            name='oDegerlendirme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koustaj.degerlendirme'),
        ),
    ]
