# Generated by Django 3.2.9 on 2022-10-28 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koustaj', '0005_auto_20221028_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True, verbose_name=' No')),
                ('password', models.CharField(max_length=50, verbose_name='Şifre')),
                ('epostaa', models.EmailField(max_length=254)),
                ('ogrenci_isim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koustaj.ogrencibilgi')),
                ('ogretmen_isim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koustaj.ogretmen')),
            ],
            options={
                'verbose_name': 'Giriş Bilgileri',
                'verbose_name_plural': 'Giriş Bİlgileri',
            },
        ),
    ]
