# Generated by Django 3.2.9 on 2022-11-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koustaj', '0007_auto_20221030_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrencibilgi',
            name='ogrenci_telefon',
        ),
        migrations.AddField(
            model_name='ogrencibilgi',
            name='epostaa',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='degerlendirme',
            name='degerlendirme',
            field=models.BooleanField(default=False, null=True, verbose_name='Değerlendirme'),
        ),
        migrations.AlterField(
            model_name='degerlendirme',
            name='staj_basvuru',
            field=models.BooleanField(default=False, null=True, verbose_name='Staj Başvuru Formu'),
        ),
        migrations.AlterField(
            model_name='degerlendirme',
            name='staj_degerlendirme',
            field=models.BooleanField(default=False, null=True, verbose_name='Staj Değerlendirme Formu'),
        ),
        migrations.AlterField(
            model_name='degerlendirme',
            name='staj_rapor',
            field=models.BooleanField(default=False, null=True, verbose_name='Staj Raporu'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='devlet_katkisi',
            field=models.BooleanField(default=False, null=True, verbose_name='Devlet Katkısı'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='faaliyet_alani',
            field=models.CharField(max_length=50, null=True, verbose_name='Faaliyet Alanı'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='firma_adi',
            field=models.CharField(max_length=200, null=True, verbose_name='Firma Adı'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='il',
            field=models.CharField(max_length=50, null=True, verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='ilçe',
            field=models.CharField(max_length=50, null=True, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='unvan',
            field=models.CharField(max_length=50, null=True, verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='yetkil_ad',
            field=models.CharField(max_length=50, null=True, verbose_name='Yetkili Ad'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='yetkili_soyad',
            field=models.CharField(max_length=50, null=True, verbose_name='Yetkili Soyad'),
        ),
        migrations.AlterField(
            model_name='giris',
            name='epostaa',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='giris',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='Şifre'),
        ),
        migrations.AlterField(
            model_name='ogrencibasvuru',
            name='baslama_tarih',
            field=models.DateField(null=True, verbose_name='Başlama Tarihi'),
        ),
        migrations.AlterField(
            model_name='ogrencibasvuru',
            name='bitis_tarih',
            field=models.DateField(null=True, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='ogrencibasvuru',
            name='staj_sorumlusu',
            field=models.CharField(max_length=50, null=True, verbose_name='Staj Sorumlusu'),
        ),
        migrations.AlterField(
            model_name='ogrencibasvuru',
            name='staj_tur',
            field=models.CharField(max_length=50, null=True, verbose_name='Staj Tür'),
        ),
        migrations.AlterField(
            model_name='ogrencibasvuru',
            name='tarih',
            field=models.DateField(null=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='ogrencibasvuru',
            name='uyruk',
            field=models.CharField(max_length=50, null=True, verbose_name='Uyruk'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='basvuru_dosyası',
            field=models.BooleanField(default=False, null=True, verbose_name='Başvuru Dosyası'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_ad',
            field=models.CharField(max_length=50, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_adres',
            field=models.CharField(max_length=200, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_bolum',
            field=models.CharField(max_length=50, null=True, verbose_name='Bölüm'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_dogum_tarihi',
            field=models.DateField(null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_dogum_yeri',
            field=models.CharField(max_length=50, null=True, verbose_name='Doğum Yeri'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_eposta',
            field=models.EmailField(max_length=254, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_fakulte',
            field=models.CharField(max_length=50, null=True, verbose_name='Fakülte'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_kayıt_tarihi',
            field=models.DateField(null=True, verbose_name='Öğren Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='ogrencibilgi',
            name='ogrenci_soyad',
            field=models.CharField(max_length=50, null=True, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='ogretmen',
            name='ogretmen_ad',
            field=models.CharField(max_length=50, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='ogretmen',
            name='ogretmen_bolum',
            field=models.CharField(max_length=50, null=True, verbose_name='Bölüm'),
        ),
        migrations.AlterField(
            model_name='ogretmen',
            name='ogretmen_fakulte',
            field=models.CharField(max_length=50, null=True, verbose_name='Fakülte'),
        ),
        migrations.AlterField(
            model_name='ogretmen',
            name='ogretmen_soyad',
            field=models.CharField(max_length=50, null=True, verbose_name='Soyad'),
        ),
    ]
