# Generated by Django 3.2.9 on 2022-11-14 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('koustaj', '0008_auto_20221103_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrencibilgi',
            name='kullanici',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
