# Generated by Django 3.2.9 on 2022-11-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koustaj', '0009_ogrencibilgi_kullanici'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ogrencibilgi',
            old_name='basvuru_dosyası',
            new_name='basvurudosyasi',
        ),
    ]
