# Generated by Django 3.2.9 on 2022-11-14 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koustaj', '0010_rename_basvuru_dosyası_ogrencibilgi_basvurudosyasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='oBasvuru',
        ),
        migrations.AddField(
            model_name='ogrencibilgi',
            name='ofirma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koustaj.firma'),
        ),
    ]
