# Generated by Django 3.2.9 on 2022-11-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koustaj', '0011_auto_20221114_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrencibasvuru',
            name='staj_tur',
        ),
        migrations.AddField(
            model_name='ogrencibilgi',
            name='staj_tur',
            field=models.CharField(max_length=50, null=True, verbose_name='Staj Tür'),
        ),
    ]
