# Generated by Django 3.2.9 on 2022-11-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koustaj', '0012_auto_20221115_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrencibilgi',
            name='ogretmen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koustaj.ogretmen'),
        ),
    ]
