# Generated by Django 3.2.9 on 2022-11-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koustaj', '0013_ogrencibilgi_ogretmen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degerlendirme',
            old_name='staj_basvuru',
            new_name='staj_basvuru_formu',
        ),
        migrations.RemoveField(
            model_name='degerlendirme',
            name='degerlendirme',
        ),
        migrations.RemoveField(
            model_name='degerlendirme',
            name='staj_degerlendirme',
        ),
        migrations.RemoveField(
            model_name='degerlendirme',
            name='staj_rapor',
        ),
        migrations.AddField(
            model_name='degerlendirme',
            name='staj_defteri',
            field=models.BooleanField(default=False, null=True, verbose_name='Staj Defteri'),
        ),
        migrations.AddField(
            model_name='degerlendirme',
            name='staj_evragi',
            field=models.BooleanField(default=False, null=True, verbose_name='Staj Evrağı'),
        ),
        migrations.AddField(
            model_name='degerlendirme',
            name='staj_not',
            field=models.IntegerField(default=False, null=True, verbose_name='Not'),
        ),
    ]
