# Generated by Django 3.2.9 on 2022-11-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koustaj', '0014_auto_20221115_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degerlendirme',
            name='staj_defteri',
            field=models.BooleanField(default=False, null=True, verbose_name='Staj'),
        ),
    ]
