# Generated by Django 3.2.9 on 2022-11-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koustaj', '0015_alter_degerlendirme_staj_defteri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrencibilgi',
            name='kullanici',
        ),
        migrations.RemoveField(
            model_name='ogrencibilgi',
            name='odegerlendirme',
        ),
        migrations.RemoveField(
            model_name='ogrencibilgi',
            name='ofirma',
        ),
        migrations.RemoveField(
            model_name='ogrencibilgi',
            name='ogretmen',
        ),
    ]
