# Generated by Django 3.2.9 on 2022-11-16 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koustaj', '0016_auto_20221116_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrencibilgi',
            name='odegerlendirme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koustaj.degerlendirme'),
        ),
        migrations.AddField(
            model_name='ogrencibilgi',
            name='ofirma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koustaj.firma'),
        ),
        migrations.AddField(
            model_name='ogrencibilgi',
            name='ogretmen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koustaj.ogretmen'),
        ),
    ]
