# Generated by Django 3.2.9 on 2022-11-16 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('koustaj', '0018_auto_20221116_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrencibilgi',
            name='kullanici',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ogrencibilgi',
            name='odegerlendirme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koustaj.degerlendirme'),
        ),
        migrations.AddField(
            model_name='ogrencibilgi',
            name='ofirma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koustaj.firma'),
        ),
        migrations.AddField(
            model_name='ogrencibilgi',
            name='ogretmen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koustaj.ogretmen'),
        ),
    ]
